# CircleCI configuration file
# This comment to force a rebuild after cleaning up diff-lcs gem

version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/ruby:3.3.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.5.9
          RAILS_ENV: test
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      - restore_cache:
          key: app{{ checksum "Gemfile.lock" }}

      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: Bundle install
          command: bundle install

      - save_cache:
          key: app-{{ checksum "Gemfile.lock" }}
          paths:
             - vendor/bundle

      # Wait for postgres
      - run:
          name: Wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Config database
          environment:
            - RAILS_ENV: test
          command: |
            echo 'test:
              adapter: postgresql
              database: apptestdb
              username: postgres
              password: password
              host: localhost
            ' > config/database.yml
      - run:
          name: Setup Database
          command: bundle exec rake db:create db:schema:load --trace

      - run:
          name: Run RSpec
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" |circleci tests split --split-by=timings)
          when: always