# CircleCI configuration file

version: 2.1

orbs:
  ruby: circleci/ruby@2.1.2
  node: circleci/node@5.0.2

workflows:
  version: 2
  build:
    jobs:
      - "build_rails_7_1"

jobs:
  "build_rails_7_1":
    docker:
      - image: cimg/ruby:3.3.1-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run: ruby --version
      - run: node --version
      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
      - run:
          name: Database setup
          command: |
            bundle exec bin/rails active_storage:install
            bundle exec bin/rails db:structure:load
      - run:
          name: RSpec
          command: |
            export RAILS_ENV=test
            bundle exec rspec
    